sudo: required
services:
  - docker

before_install:
  - docker build -p 80:80 -t johnrattz/docker-react -f Dockerfile.dev .

script: # If this command returns 0, the deploy step will be run.
  - docker run johnrattz/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-166068999731"
  bucket_path: "docker-react" # Same as `app` - the app name.
  on: # Only deploy when the `master` branch is changed on GitHub.
    branch: master
  # TODO: Does this need to have a `secure` member map to $AWS_ACCESS_KEY instead?
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
